server:
  port: 8081
  servlet:
    session:
      timeout: 1800
      # 기본 단위는 초이고, 단위가 '60'초이기 때문에 130처럼 2분 10초로 설정하는 경우, session.getMaxInactiveInterval() = 120으로 절사되어 나옴.
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
# 스웨거 Spring boot 2.6.2버전 이후 sping.mvc.pathmatch.matching-strategy의 값이
# ant_path_matcher -> path_pattern_parser로 변경되어 오류 발생 가능함
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging.level:
  root: warn
  org.hibernate.SQL: debug
  # org.hibernate.type: trace